### ISSUE TITLE
Garbled view when using FZF with additional qf formatter plugin

### ISSUE THREAD

**Issue by ajitid** [kevinhwang91/nvim-bqf#56] opened 2022-02-21 04:31 UTC
### Neovim version (nvim -v | head -n1)

NVIM v0.7.0-dev+1109-gfaeff49cb

### Operating system/version

Ubuntu 21.04 on WSL2

### How to reproduce the issue

1. Install https://gitlab.com/yorickpeterse/nvim-pqf
2. Put items in quick fix list 

![image](https://user-images.githubusercontent.com/26769888/154889389-897b5749-f96a-44f2-ad2a-106576ccca5c.png)

3. Now open fzf using `zf` keybinding

### Expected behavior

Text in FZF list should be same as what we see in quick fix list

### Actual behavior

Garbled text is being seen (notice many `{m`, `[m` and numbers across the list)

![image](https://user-images.githubusercontent.com/26769888/154889576-fb0cb9b4-6a54-4726-bbdb-b7b64b3f6e8f.png)

This, as you previously mentioned, could be related to concealing.

**Comment by kevinhwang91** [comment] 2022-02-21 04:35
The reason is `nvim-pqf` using `conceal` to hide `{}<>` chars. The items as a source for fzf is not supported `conceal` for now, I will try to fix if I have times.

**Comment by kevinhwang91** [comment] 2022-02-21 14:23
Please try `dev` branch.

**Comment by ajitid** [comment] 2022-02-21 14:32
I can still see those messy characters.

**Comment by kevinhwang91** [comment] 2022-02-21 14:40
Make sure you have changed the `dev` branch and updated the code. I have tested under clean ENV with docker is fine, only load `nvim-bqf`, `fzf` and `nvim-pqf.git`.

**Comment by ajitid** [comment] 2022-02-21 14:41
What docker image did you use?

**Comment by kevinhwang91** [comment] 2022-02-21 14:42
`anatolelucet/neovim:0.6.0`

**Comment by kevinhwang91** [comment] 2022-02-21 15:06
Waiting for your solution, maybe some potential bugs I haven't thought about.

**Comment by ajitid** [comment] 2022-02-21 15:44
@kevinhwang91 so I removed all other plugins, even removed the whole config, updated fzf, updated neovim — but I still couldn't reproduce the right behavaior on my machine, I'll have to adjust with it I guess 🤷‍♂️

**Comment by kevinhwang91** [comment] 2022-02-21 15:58
I also can't reproduce the screenshot you provided. `main` branch only with the issue for extra `{`, I think you should check out the fzf and your terminal ansi escape code. 
![image](https://user-images.githubusercontent.com/17562139/154988312-57a33a28-4f7b-4598-b500-4cabadf4136a.png)

FYI: you can debug bqf by yourself if you want.

1. `tail -f ~/.cache/nvim/bqf.log`
2. Add `log.debug(processed_line)` under `*/nvim-bqf/lua/bqf/filter/fzf.lua:172`
3. `BQF_LOG=warn nvim` and reproduce the issue and get the log.

**Comment by ajitid** [comment] 2022-02-21 16:12
So the culprit was my default shell, Fish. I did `chsh` and switched to `bash` and now it works fine. 

![image](https://user-images.githubusercontent.com/26769888/154991239-ce8ca573-4cd1-4a51-af98-3139deb37da1.png)
 
Oddly, when I switched to fish from bash, it worked just fine too. I have dozens of stuff configured in Fish, it could be one of the those things

**Comment by kevinhwang91** [comment] 2022-02-21 16:19
Thanks for your feedback, I have merged the patch.

**Closed by kevinhwang91** 2022-02-21 16:19 UTC
Labels: bug

**Comment by wodesuck** [comment] 2022-05-22 10:19
@ajitid I found that should be a bug of fzf, and I fix it in https://github.com/junegunn/fzf/pull/2828

**Comment by ajitid** [comment] 2022-05-22 10:21
Oh, thank you so much @wodesuck!
