### ISSUE TITLE
Moving through the qf list pollutes v:oldfiles

### ISSUE THREAD

**Issue by ahmedelgabri** [kevinhwang91/nvim-bqf#11] opened 2021-04-05 23:09 UTC
First of all this plugin is great! so thanks for that.

I found out that moving through the qf list, will populate `v:oldfiles`, you can easily check that by running `:oldfiles`. So any plugin that depends on this information to show most recently used files will become useless. Example: [`vim-startify`](https://github.com/mhinz/vim-startify)

It will be great if the plugin can avoid doing that.

**Comment by kevinhwang91** [comment] 2021-04-06 15:18
I found this issue when I was developing the bqf. `bw` can wipe the recent record but `bd` can't now, if bqf uses `bw` to restore the unpreviewed status, user can't enter the buffer again which is wiped by `bw`. 

I use my personal mru as a workaround. 
However, you let me know someone care about this issue, I will give it a try to fix it.

**Comment by kevinhwang91** [comment] 2021-04-07 12:42
@ahmedelgabri Do you manually run `wshada` or `rshada`？ If not，I think wipe the unnecessary buffers before exit is a simple way to solve this issue.

**Comment by kevinhwang91** [comment] 2021-04-07 13:15
```vim
au VimLeavePre * let unlist = filter(nvim_list_bufs(), '!buflisted(v:val)') |
            \ if !empty(unlist) |
            \ exe 'sil! bw  ' . join(unlist, ' ') |
            \ endif
```
I think the above snippet code work for me. The original issue is from shada. I don't use shada because it slows down as the mru grows, and bad design of synchronization.
If this code snippet good for you, I will close this issue and add it to FAQ.

**Comment by ahmedelgabri** [comment] 2021-04-07 22:02
This is what I use with [shada](https://github.com/ahmedelgabri/dotfiles/blob/c5b7a876f338801dc280b36e4ab81130694482d2/config/.vim/plugin/settings.vim#L212-L229)

```vim
if exists('$SUDO_USER')               " don't create root-owned files
  set shada=
else
  " default in nvim: !,'100,<50,s10,h
  set shada=!,'100,<500,:10000,/10000,s10,h
  augroup MyNeovimShada
    autocmd!
    autocmd CursorHold,FocusGained,FocusLost * rshada|wshada
  augroup END
endif
```

I'm curious to know what do you use then if you don't use shada?

**Comment by kevinhwang91** [comment] 2021-04-08 10:23
I see, you manually run `rshada` and `wshada`, so the code doesn't work for you.

Sorry for my ambiguous expression, I use my own mru script instead of `v:oldfiles` implemented by shada.

**Comment by kevinhwang91** [comment] 2021-04-09 12:55
How about below snippet?
```vim
autocmd CursorHold,FocusGained,FocusLost * if &ft != 'qf' | rshada | wshada | endif
au VimLeavePre * let unlist = filter(nvim_list_bufs(), '!buflisted(v:val)') |
            \ if !empty(unlist) |
            \ exe 'sil! bw! ' . join(unlist, ' ') |
            \ endif
```

**Comment by kevinhwang91** [comment] 2021-05-30 20:23
After spending 3 hours dive into the source code of nvim, I have found the essential issue and fixed.

**Closed by kevinhwang91** 2021-05-30 20:23 UTC
Labels: bug

**Comment by ahmedelgabri** [comment] 2021-05-31 07:19
I have already updated the plugin but I still see the preview buffers in `v:oldfiles`

**Comment by kevinhwang91** [comment] 2021-05-31 07:20
Did you only preview the buffer without entering?

**Comment by kevinhwang91** [comment] 2021-05-31 07:22
Oh, I know the issue... 
> I see, you manually run `rshada` and `wshada`, so the code doesn't work for you.
> 
> Sorry for my ambiguous expression, I use my own mru script instead of `v:oldfiles` implemented by shada.

**Comment by ahmedelgabri** [comment] 2021-05-31 07:23
> Did you only preview the buffer without entering?

yes

**Comment by kevinhwang91** [comment] 2021-05-31 07:24
> > Did you only preview the buffer without entering?
> 
> yes

Could you try again without running `rshada` and `wshada` manually?

**Comment by kevinhwang91** [comment] 2021-05-31 07:35
`autocmd CursorHold,FocusGained,FocusLost * if &bt == '' | rshada | wshada | endif` will work for you. I don't suggest you run `rshada` and `wshada` via `autocmd` which will destroy your location jump.

**Comment by ahmedelgabri** [comment] 2021-05-31 07:39
This is how it works after the update, first with the `shada` autocmd & then without it. Notice also the preview glitch when I press `q` to quit it sticks at the top of the screen for some reason & that is count as a buffer open too.


https://user-images.githubusercontent.com/63876/120157857-be5e5900-c1f3-11eb-98af-3103be9991c7.mp4

**Comment by kevinhwang91** [comment] 2021-05-31 07:47
I can't reproduce the issue for preview glitch, please open a new issue and reproduce it in a mini configuration.

**Comment by ahmedelgabri** [comment] 2021-05-31 07:50
> I can't reproduce the issue for preview glitch, please open a new issue and reproduce it in a mini configuration.

Sure, will debug more thoroughly to check if it's an issue on my end first or not.

> > `autocmd CursorHold,FocusGained,FocusLost * if &bt == '' | rshada | wshada | endif` will work for you. I don't suggest you run `rshada` and `wshada` via `autocmd` which will destroy your location jump.
> 
> Does this snippet work for you?

Yes, thanks 👍🏼
