### ISSUE TITLE
bqf preview window stuck when jumps are used

### ISSUE THREAD

**Issue by danielnehrig** [kevinhwang91/nvim-bqf#70] opened 2022-06-07 21:58 UTC
### Neovim version (nvim -v | head -n1)

any version

### Operating system/version

macOs

### How to reproduce the issue

1. fill qf list
2. go to qf window
3. bqf shows the preview window popup for the file
4. press ctrl+o to utilize jumplist

### Expected behavior

jumping out of the qf window closes the bqf preview popup

### Actual behavior

jumping out of the qf window with ctrl+o leaves the pop up open and overlays the buffer

**Comment by kevinhwang91** [comment] 2022-06-07 22:02
Have you disabled bqf and tried built-in qf? This is built-in qf behavior.

**Comment by danielnehrig** [comment] 2022-06-13 23:15
im talkin about the buffer preview window if that wasn't clear

**Comment by kevinhwang91** [comment] 2022-06-14 03:14
I can't reproduce it, please use a minimal config and more detailed steps, maybe I misunderstand what you are talking about.

**Comment by danielnehrig** [comment] 2022-06-15 16:58
minimal
```lua
-- File To reproduce issues with a minimal setup
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "nvim-telescope/telescope.nvim",
        requires = {
          "nvim-lua/plenary.nvim",
        },
      },
      { "kevinhwang91/nvim-bqf", ft = "qf" }, -- better quickfix
      {
        "nvim-treesitter/nvim-treesitter",
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
_G.load_config = function()
  require("telescope").setup()
  vim.wo.foldmethod = "expr"
  vim.wo.foldexpr = "nvim_treesitter#foldexpr()"
  vim.wo.foldnestmax = 3
  vim.wo.foldminlines = 1

  vim.keymap.set({ "n" }, "<space>ff", ":Telescope find_files<CR>", {
    silent = true,
  })
  require("nvim-treesitter.configs").setup({
    ensure_installed = { "lua" }, -- one of "all", "maintained" (parsers with maintainers), or a list of languages
    highlight = {
      enable = true,
    },
    indent = {
      enable = true,
    },
    autotag = {
      enable = true,
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system({
    "git",
    "clone",
    "--depth=1",
    "https://github.com/wbthomason/packer.nvim",
    install_path,
  })
end
load_plugins()
require("packer").sync()
vim.cmd(
  [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
)
```

https://user-images.githubusercontent.com/4050749/173883814-d6cd0639-ebfb-43ea-a5a3-d6e63e44b293.mp4

**Comment by danielnehrig** [comment] 2022-06-15 17:02
long story short when you have 2 windows one is a normal buffer the other is a qf window and you're inside the qf window and then use the jumplist to jump back the qf window will be a buffer when that happens the bqf buffer preview popup should close but it stays open

**Comment by danielnehrig** [comment] 2022-06-15 17:04
for demonstration purposes i then in the video closed the QF window or rather the now buffer window since we jumped back in the jumplist history to show the full effect of the bug which makes vim unusable since nothing can be done to get rid of the preview pop up

**Comment by kevinhwang91** [comment] 2022-06-15 17:18
Do you mean you want the preview window to be closed after qf buffer is hidden?

**Comment by kevinhwang91** [comment] 2022-06-15 17:24
Fixed now.

**Closed by kevinhwang91** 2022-06-15 17:24 UTC
Labels: bug

**Comment by danielnehrig** [comment] 2022-06-17 01:00
can confirm solves the issue thanks for the fast fix and response
